set wt [gi::getWindowTypes dbParameterEditor]
db::setAttr wt.geometry -value "625x400+55+105"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes seSymbol]
db::setAttr wt.geometry -value "1632x947+133+93"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes giConsole]
db::setAttr wt.geometry -value "1910x1020+5+55"
db::setAttr wt.maximized -value "true"
set wt [gi::getWindowTypes seSchematic]
db::setAttr wt.geometry -value "1910x1020+5+55"
db::setAttr wt.maximized -value "true"
set wt [gi::getWindowTypes leLayout]
db::setAttr wt.geometry -value "1910x1020+19+28"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes teText]
db::setAttr wt.geometry -value "1910x1020+5+55"
db::setAttr wt.maximized -value "true"
set wt [gi::getWindowTypes deBookmarkManager]
db::setAttr wt.geometry -value "530x400"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes dbFindReplace]
db::setAttr wt.geometry -value "580x620"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes xtJobMonitor]
db::setAttr wt.geometry -value "800x600+158+246"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes dmLibraryManager]
db::setAttr wt.geometry -value "660x600+670+237"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes saAnalyzeResults]
db::setAttr wt.geometry -value "788x794+55+105"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes embedResultsViewer]
db::setAttr wt.geometry -value "1024x768+644+115"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes embedWaveViewer]
db::setAttr wt.geometry -value "1910x1020+5+55"
db::setAttr wt.maximized -value "true"
set wt [gi::getWindowTypes saConsoleHSPICE]
db::setAttr wt.geometry -value "600x517+5+55"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes saConsoleFineSimProVCS]
db::setAttr wt.geometry -value "600x517+55+105"
db::setAttr wt.maximized -value "false"
unset wt
