set wt [gi::getWindowTypes seSchematic]
db::setAttr wt.geometry -value "1632x947+192+128"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes giConsole]
db::setAttr wt.geometry -value "600x300+644+365"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes deBookmarkManager]
db::setAttr wt.geometry -value "530x400"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes dbFindReplace]
db::setAttr wt.geometry -value "580x620"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes xtJobMonitor]
db::setAttr wt.geometry -value "800x600+5+55"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes dmLibraryManager]
db::setAttr wt.geometry -value "660x600+50+77"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes xtTextViewer]
db::setAttr wt.geometry -value "1471x600+291+170"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes dbTechnologyManager]
db::setAttr wt.geometry -value "350x400+55+105"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes saAnalyzeResults]
db::setAttr wt.geometry -value "788x794+399+167"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes embedResultsViewer]
db::setAttr wt.geometry -value "1024x768+55+105"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes embedWaveViewer]
db::setAttr wt.geometry -value "1910x1020+5+55"
db::setAttr wt.maximized -value "true"
set wt [gi::getWindowTypes saConsoleHSPICE]
db::setAttr wt.geometry -value "1910x1020+5+55"
db::setAttr wt.maximized -value "true"
unset wt
