set wt [gi::getWindowTypes seSchematic]
db::setAttr wt.geometry -value "1632x947+152+73"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes giConsole]
db::setAttr wt.geometry -value "600x300+617+443"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes deBookmarkManager]
db::setAttr wt.geometry -value "530x400"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes dbFindReplace]
db::setAttr wt.geometry -value "580x620"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes xtJobMonitor]
db::setAttr wt.geometry -value "800x600+5+55"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes dmLibraryManager]
db::setAttr wt.geometry -value "973x600+162+91"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes xtTextViewer]
db::setAttr wt.geometry -value "1471x600+291+170"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes embedResultsViewer]
db::setAttr wt.geometry -value "1024x768+55+105"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes embedWaveViewer]
db::setAttr wt.geometry -value "1910x1020+5+55"
db::setAttr wt.maximized -value "true"
set wt [gi::getWindowTypes saConsoleHSPICE]
db::setAttr wt.geometry -value "600x517+557+113"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes saConsoleFineSimPro]
db::setAttr wt.geometry -value "887x517+594+182"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes saConsoleFineSimProVCS]
db::setAttr wt.geometry -value "895x517+581+206"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes saConsolePrimeSim]
db::setAttr wt.geometry -value "958x517+637+185"
db::setAttr wt.maximized -value "false"
unset wt
