set wt [gi::getWindowTypes giConsole]
db::setAttr wt.geometry -value "600x300+344+115"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes deBookmarkManager]
db::setAttr wt.geometry -value "530x400"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes dbFindReplace]
db::setAttr wt.geometry -value "580x620"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes xtJobMonitor]
db::setAttr wt.geometry -value "800x600+55+105"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes dmLibraryManager]
db::setAttr wt.geometry -value "1060x600+670+237"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes embedResultsViewer]
db::setAttr wt.geometry -value "1024x768+105+155"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes embedWaveViewer]
db::setAttr wt.geometry -value "1024x766+155+207"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes saConsoleFineSimProVCS]
db::setAttr wt.geometry -value "600x517+5+55"
db::setAttr wt.maximized -value "false"
unset wt
