set wt [gi::getWindowTypes seSchematic]
db::setAttr wt.geometry -value "1910x1020+5+55"
db::setAttr wt.maximized -value "true"
set wt [gi::getWindowTypes giConsole]
db::setAttr wt.geometry -value "1910x1020+5+55"
db::setAttr wt.maximized -value "true"
set wt [gi::getWindowTypes leLayout]
db::setAttr wt.geometry -value "1910x1020+5+55"
db::setAttr wt.maximized -value "true"
set wt [gi::getWindowTypes drEditor]
db::setAttr wt.geometry -value "152x175+55+105"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes deBookmarkManager]
db::setAttr wt.geometry -value "530x400"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes dbFindReplace]
db::setAttr wt.geometry -value "618x620+55+105"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes xtJobMonitor]
db::setAttr wt.geometry -value "800x600+528+221"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes dmLibraryManager]
db::setAttr wt.geometry -value "1060x600+367+247"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes xtTextViewer]
db::setAttr wt.geometry -value "800x600+630+144"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes heEditor]
db::setAttr wt.geometry -value "750x750+196+116"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes embedResultsViewer]
db::setAttr wt.geometry -value "1024x768+63+670"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes embedWaveViewer]
db::setAttr wt.geometry -value "1910x1020+5+55"
db::setAttr wt.maximized -value "true"
set wt [gi::getWindowTypes saConsoleHSPICE]
db::setAttr wt.geometry -value "600x517+5+55"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes saConsoleFineSimPro]
db::setAttr wt.geometry -value "600x517+127+155"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes saConsoleFineSimProVCS]
db::setAttr wt.geometry -value "600x517+118+115"
db::setAttr wt.maximized -value "false"
unset wt
