set wt [gi::getWindowTypes seSchematic]
db::setAttr wt.geometry -value "1632x947+50+100"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes seSymbol]
db::setAttr wt.geometry -value "1632x947+5+55"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes giConsole]
db::setAttr wt.geometry -value "600x300+5+699"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes leLayout]
db::setAttr wt.geometry -value "1632x947+181+79"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes deBookmarkManager]
db::setAttr wt.geometry -value "530x400"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes dbFindReplace]
db::setAttr wt.geometry -value "580x620"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes xtJobMonitor]
db::setAttr wt.geometry -value "800x600+100+150"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes dmLibraryManager]
db::setAttr wt.geometry -value "795x600+68+65"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes xtTextViewer]
db::setAttr wt.geometry -value "800x600+200+103"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes heEditor]
db::setAttr wt.geometry -value "750x750+78+79"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes embedResultsViewer]
db::setAttr wt.geometry -value "1024x768+274+196"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes embedWaveViewer]
db::setAttr wt.geometry -value "1910x1020+5+55"
db::setAttr wt.maximized -value "true"
set wt [gi::getWindowTypes saConsoleHSPICE]
db::setAttr wt.geometry -value "992x754+472+199"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes saConsoleFineSimPro]
db::setAttr wt.geometry -value "977x604+588+285"
db::setAttr wt.maximized -value "false"
unset wt
