#!/bin/sh
ulimit -c 0
total=0
pathsize=`/usr/bin/du -s --block-size=1 /mnt/vol_NFS_rh003/Est_VLSI_II_2024/jmorales/EL5807/Tarea2/synopsys_custom/nor2in.icv.lvs/run_details --exclude=group | awk '{print $1}'`
total=$(($total+$pathsize))
group=0
group=`/usr/bin/du -s --block-size=1 /mnt/vol_NFS_rh003/Est_VLSI_II_2024/jmorales/EL5807/Tarea2/synopsys_custom/nor2in.icv.lvs/run_details/group | awk '{print $1}'`
echo $group > /mnt/vol_NFS_rh003/Est_VLSI_II_2024/jmorales/EL5807/Tarea2/synopsys_custom/nor2in.icv.lvs/run_details/group/duse_group.tmp && \
mv /mnt/vol_NFS_rh003/Est_VLSI_II_2024/jmorales/EL5807/Tarea2/synopsys_custom/nor2in.icv.lvs/run_details/group/duse_group.tmp /mnt/vol_NFS_rh003/Est_VLSI_II_2024/jmorales/EL5807/Tarea2/synopsys_custom/nor2in.icv.lvs/run_details/group/duse_group
pathsize=`/usr/bin/du -s --block-size=1 /mnt/vol_NFS_rh003/Est_VLSI_II_2024/jmorales/EL5807/Tarea2/synopsys_custom/nor2in.icv.lvs/nor2in.TOP_LAYOUT_ERRORS | awk '{print $1}'`
total=$(($total+$pathsize))
pathsize=`/usr/bin/du -s --block-size=1 /mnt/vol_NFS_rh003/Est_VLSI_II_2024/jmorales/EL5807/Tarea2/synopsys_custom/nor2in.icv.lvs/pydb | awk '{print $1}'`
total=$(($total+$pathsize))
echo $total > /mnt/vol_NFS_rh003/Est_VLSI_II_2024/jmorales/EL5807/Tarea2/synopsys_custom/nor2in.icv.lvs/run_details/duse_manager_res.tmp && \
mv /mnt/vol_NFS_rh003/Est_VLSI_II_2024/jmorales/EL5807/Tarea2/synopsys_custom/nor2in.icv.lvs/run_details/duse_manager_res.tmp /mnt/vol_NFS_rh003/Est_VLSI_II_2024/jmorales/EL5807/Tarea2/synopsys_custom/nor2in.icv.lvs/run_details/duse_manager_res
